config/routes.rb
Rails.application.routes.draw do
  root "physicians#index"
  devise_for :users
  resources :patients
  resources :physicians do
  resources :appointments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :physicians, through: :appointments
  belongs_to :user
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :patients
  has_many :physicians
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phd])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phd])

    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [ :show, :edit, :update, :destroy]
  def index
    @appointments = current_user.appointments.all
  end

  def show
  end
  
  def new
    @appointment = current_user.physician.appointments.new
  end

  def create
    @appointment = current_user.physician.apppointments.new(the_params)
    if @appointment.save
      redirect_to root_path
    else 
      render :new
  end
end
  def edit
  end

  def update
    if @appointment.update(the_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to root_path
  end

  private
   def set_appointment
    @appointment = current_user.appointments.find(params[:id])
   end

   def the_params
    params.require(:appointment).permit(:name)
   end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_user
  before_action :set_patient, only: [ :show, :edit, :update, :destroy]
  
  def index
  @user = current_user.first_time
    if @user == nil
        current_user[:first_time] = false
      @patient = Patient.new
    else 
      binding.pry
      redirect_to patients_path(@patient)
    end
    @patient = current_user.patients.all
  end

  def show
  end
  
  def new
    @patient = Patient.new
  end

  def create
    @patient = current_user.patients.new(the_params)
    if @patient.save
      redirect_to patients_path(@patient)
    else 
      render :new
  end
end

  def edit
  end

  def update
    if @patient.update(the_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to root_path
  end

  private
   def set_patient
    @patient = Patient.find(params[:id])
   end

   def the_params
    params.require(:patient).permit(:name, :admin)
   end
   def set_user
    @user = current_user
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_user
  before_action :set_physician, only: [ :show, :edit, :update, :destroy]
  def index
    @user = current_user.first_time
    if @user == nil
      @user = current_user.phd
      if @user == true
        current_user[:first_time] = false
      @physician = Physician.new
    else 
      redirect_to patients_path
    end
    @physicians = current_user.physicians.all
  end
end
  def show
  end
  
  def new
    
  end

  def create
    @physician = Physician.new(the_params)
    if @physician.save
      redirect_to @physician
    else 
      render :new
  end
end
  def edit
  end

  def update
    if @physician.update(the_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @physician.destroy
    redirect_to root_path
  end

  private
   def set_physician
    @physician = Physician.find(params[:id])
   end

   def the_params
    params.require(:physician).permit(:name, :user_id)
   end
   def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dochelper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<h1>Patients#edit</h1>
<p>Find me in app/views/patients/edit.html.erb</p>

app/views/patients/index.html.erb
<h1>Hello <%= current_user.patients.name %></h1>

<h3>Here is a list of your appointment for today</h3>

<table class="ui striped inverted table">
  <tbody class="center aligned">
<% Patient.each do |song| %>
<tr>
        <td class="right aligned">
<h2><%= song.name %></h2>
</td><td>
</td>
</tr>
<% end%>
</tbody>
</table>

app/views/patients/new.html.erb
<h1>Patients#new</h1>
<p>Find me in app/views/patients/new.html.erb</p>

app/views/patients/show.html.erb
<h1>Patients#show</h1>
<p>Find me in app/views/patients/show.html.erb</p>

app/views/physicians/edit.html.erb
<h1>Physicians#edit</h1>
<p>Find me in app/views/physicians/edit.html.erb</p>

app/views/physicians/index.html.erb
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>


<h3>umm who are you</h3>

app/views/physicians/new.html.erb
<h1>Welcome Dr. <%= current_user.last_name %></h1>
<%=  %>
<% @namer = "#{current_user.first_name} #{current_user.last_name}" %>
<% @addminn = false %>
<%= form_for @physician do |f| %>
    <div>
    <%= f.hidden_field :name, value: @namer %>
    </div>
       <div>
    <%= f.hidden_field :admin, value: @addminn %>
    </div>
    <%= f.submit %>

<% end %>

app/views/physicians/show.html.erb
<nav><%= link_to "New Appointment", new_physician_appointment_path(params) %> </nav>
<h1>Hello <%= current_user.physicians.name %></h1>

<h3>Here is a list of your appointment for today</h3>